### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by anubhavroy** [IAmigos/avatar-image-generator#4]
Hi,
How can I use this code just for inference only with your pretrained model/weights?

**Comment by StevRamos** [comment]
Hi, sorry I'm late, we were pretty busy. You can use the generate method of the avatar_generator_model class (https://github.com/IAmigos/avatar-image-generator/blob/f4f8c9809b2b6368849e5311b3629832016b298b/models/avatar_generator_model.py#L82) you have to specify the weights path in https://github.com/IAmigos/avatar-image-generator/blob/master/config.json. This works only for one image. Soon we will add a code to infer images that are in a folder. Let me know if this helps you.
